"""Intent dataset and training examples for the NLU classifier."""


from voice_assistant.config.constants import IntentType

INTENT_CORPUS: dict[IntentType, list[str]] = {
    IntentType.GREETING: [
        "hello",
        "hi there",
        "hey assistant",
        "good morning",
        "good afternoon",
        "good evening",
        "greetings",
        "howdy",
        "hello aura",
        "hey there",
        "hi",
        "nice to meet you",
    ],
    IntentType.TIME: [
        "what time is it",
        "tell me the time",
        "current time please",
        "what is the current time",
        "do you have the time",
        "could you tell me what time it is",
        "what's the time right now",
        "clock time",
    ],
    IntentType.DATE: [
        "what is today's date",
        "what's the date today",
        "tell me today's date",
        "what day is it",
        "which day of the week is it",
        "what is the date",
        "today's calendar date",
        "current date",
    ],
    IntentType.WEB_SEARCH: [
        "search the web for python tutorials",
        "google machine learning basics",
        "look up latest space news",
        "search for best restaurants nearby",
        "find information on async programming",
        "browse the web for tech news",
        "search internet for quantum computing",
        "look up fastapi docs",
    ],
    IntentType.WEATHER: [
        "what's the weather in hyderabad",
        "how is the weather in london",
        "temperature in new york",
        "is it raining in tokyo",
        "weather forecast for paris",
        "how warm is it in delhi",
        "tell me the weather outside",
        "current climate and humidity in mumbai",
        "what is the temperature today in seattle",
    ],
    IntentType.SEND_EMAIL: [
        "send an email",
        "send email to test@example.com",
        "compose an email for john",
        "send an email with subject meeting",
        "shoot an email to my manager",
        "mail john regarding the project",
        "write an email",
    ],
    IntentType.SET_REMINDER: [
        "remind me in 10 minutes to call john",
        "set a reminder for 30 seconds to test assistant",
        "remind me after two hours to take medicine",
        "create a reminder in five minutes to check the oven",
        "set an alarm for 20 seconds",
        "remind me in half an hour to submit my assignment",
        "schedule a reminder for tomorrow",
    ],
    IntentType.KNOWLEDGE: [
        "who was alan turing",
        "what is the capital of japan",
        "who is the president of france",
        "what is photosynthesis",
        "tell me about mount everest",
        "explain the theory of relativity",
        "who founded apple",
        "what is python programming",
    ],
    IntentType.ADD_COMMAND: [
        "create a command called open github that opens https://github.com",
        "add custom command open docs to open https://docs.python.org",
        "add command greet me to speak hello master",
        "create a voice command called open search",
        "register new custom command",
    ],
    IntentType.HELP: [
        "help",
        "what can you do",
        "how do i use this assistant",
        "list available commands",
        "what are your features",
        "options",
        "show help",
    ],
    IntentType.EXIT: [
        "goodbye",
        "exit",
        "quit",
        "bye",
        "shut down",
        "turn off",
        "terminate",
        "close",
        "see you later",
        "stop listening and exit",
    ],
    IntentType.CONFIRMATION_YES: [
        "yes",
        "yeah",
        "yep",
        "sure",
        "confirm",
        "send it",
        "do it",
        "proceed",
        "affirmative",
        "correct",
        "okay",
        "ok",
    ],
    IntentType.CONFIRMATION_NO: [
        "no",
        "nope",
        "nah",
        "don't send",
        "cancel",
        "stop",
        "never mind",
        "forget it",
        "abort",
    ],
    IntentType.CANCEL: [
        "cancel",
        "cancel that",
        "never mind",
        "forget it",
        "abort operation",
        "stop this",
    ],
}
